name: Build Kernel P30 Lite KSU
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Toolchain and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc bison flex libssl-dev libelf-dev ccache curl git gcc-aarch64-linux-gnu

      - name: Get Kernel Source
        run: |
          git clone --depth=1 --single-branch https://github.com/Ante0/RVL_9.1 kernel

      - name: Integrate KernelSU
        run: |
          cd kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
          echo "CONFIG_KSU=y" >> arch/arm64/configs/MAR-LX1A_defconfig
          echo "CONFIG_OVERLAY_FS=y" >> arch/arm64/configs/MAR-LX1A_defconfig

      - name: Build
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          # Questi flag servono a correggere l'errore 'yylloc' delle tue ultime immagini
          export KCFLAGS="-fcommon"
          export KCPPFLAGS="-fcommon"
          
          make O=out MAR-LX1A_defconfig
          make O=out -j$(nproc) KCFLAGS="-fcommon" KCPPFLAGS="-fcommon"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Kernel_P30_Lite_KSU
          path: kernel/out/arch/arm64/boot/Image.gz-dtb
